export type Product = {
  id: number;
  name: string;
  slug: string;
  desc: string;
  longDesc: string;
  price: number;
  tag: string;
  cat: string;
  img: string;
  badge?: "Bestseller" | "New";
  ingredients?: string[];
};

export const PRODUCTS: Product[] = [
  { id: 1, name: "Red Wine & Pomegranate Soap", slug: "red-wine-pomegranate-soap", desc: "Revitalizing & rich in antioxidants.", longDesc: "Infused with real red wine and pomegranate extracts, this soap delivers powerful antioxidants that protect and rejuvenate your skin. The natural polyphenols help fight free radicals while gently cleansing, leaving your skin feeling soft, smooth, and radiant.", price: 300, tag: "Antioxidant", cat: "Soaps", img: "/images/red_wine_soap.jpg", badge: "Bestseller", ingredients: ["Red Wine Extract", "Pomegranate", "Glycerin", "Coconut Oil"] },
  { id: 2, name: "Detox Charcoal Camel Milk Soap", slug: "detox-charcoal-camel-milk-soap", desc: "Luxuriously creamy & collagen boosting.", longDesc: "Activated charcoal draws out impurities and toxins while camel milk delivers deep moisture and collagen-boosting properties. This unique combination detoxifies without stripping, leaving skin clean and supple.", price: 250, tag: "Collagen", cat: "Soaps", img: "/images/charcoal_soap.jpg", ingredients: ["Activated Charcoal", "Camel Milk", "Shea Butter", "Olive Oil"] },
  { id: 3, name: "Coconut Lemon \u2013 Tangy/Citrus", slug: "coconut-lemon-citrus-soap", desc: "Made with fresh coconut milk \u2014 hydrating & anti-aging.", longDesc: "Fresh coconut milk meets zesty lemon in this invigorating soap. Coconut milk deeply hydrates while lemon brightens and evens skin tone. Natural anti-aging properties help reduce fine lines and keep skin youthful.", price: 260, tag: "Anti-Aging", cat: "Soaps", img: "/images/coconut_soap.jpg", ingredients: ["Coconut Milk", "Lemon Essential Oil", "Vitamin E", "Palm Oil"] },
  { id: 4, name: "Blueberry Menthol Cool Soap", slug: "blueberry-menthol-cool-soap", desc: "Cooling & revitalizing, perfect after a workout.", longDesc: "The perfect post-workout refresher. Menthol crystals provide an instant cooling sensation while blueberry antioxidants protect and nourish. Ideal for hot weather or whenever you need a refreshing pick-me-up.", price: 270, tag: "Cooling", cat: "Soaps", img: "/images/blueberry_soap.jpg", badge: "New", ingredients: ["Blueberry Extract", "Menthol Crystals", "Coconut Oil", "Aloe Vera"] },
  { id: 5, name: "Peaceful Lavender Soap", slug: "peaceful-lavender-soap", desc: "Luxurious, relaxing and soothing to the senses.", longDesc: "Pure lavender essential oil calms the mind while gentle cleansing soothes sensitive skin. Perfect for your evening routine, this soap transforms your bath into a spa-like experience.", price: 310, tag: "Relaxing", cat: "Soaps", img: "/images/lavender_soap.jpg", ingredients: ["Lavender Essential Oil", "Shea Butter", "Jojoba Oil", "Glycerin"] },
  { id: 6, name: "Honey & Almond Soap", slug: "honey-almond-soap", desc: "Hydrating & skin nourishing, 100% pure honey.", longDesc: "Made with 100% pure honey and sweet almond oil, this soap is a treat for dry skin. Honey locks in moisture naturally while almond oil softens and smooths. Rich, creamy lather that leaves skin glowing.", price: 220, tag: "Nourishing", cat: "Soaps", img: "/images/honey_soap.jpg", badge: "Bestseller", ingredients: ["Pure Honey", "Sweet Almond Oil", "Beeswax", "Vitamin E"] },
  { id: 7, name: "Neem Herbal Soap", slug: "neem-herbal-soap", desc: "Antibacterial & anti-inflammatory, purifies skin.", longDesc: "Neem has been used in Ayurvedic medicine for centuries. This soap harnesses its powerful antibacterial and anti-inflammatory properties to purify skin, fight acne, and promote a clear complexion.", price: 200, tag: "Antibacterial", cat: "Soaps", img: "/images/neem_soap.jpg", ingredients: ["Neem Leaf Extract", "Neem Oil", "Turmeric", "Tea Tree Oil"] },
  { id: 8, name: "Sandalwood Soap", slug: "sandalwood-soap", desc: "Reduces wrinkles & fine lines, made with sandalwood oil.", longDesc: "Premium sandalwood oil is renowned for its anti-aging properties. This soap helps reduce wrinkles and fine lines while imparting a warm, woody fragrance that lingers beautifully on the skin.", price: 310, tag: "Anti-Aging", cat: "Soaps", img: "/images/sandalwood_soap.jpg", ingredients: ["Sandalwood Oil", "Sandalwood Powder", "Coconut Oil", "Glycerin"] },
  { id: 9, name: "Papaya Soap", slug: "papaya-soap", desc: "Brightening & even skin tone, radiant glow.", longDesc: "Natural papain enzyme from fresh papaya gently exfoliates dead skin cells, revealing brighter, more even-toned skin underneath. Regular use promotes a radiant, healthy glow.", price: 280, tag: "Brightening", cat: "Soaps", img: "/images/papaya_soap.jpg", ingredients: ["Papaya Extract", "Papain Enzyme", "Vitamin C", "Coconut Oil"] },
  { id: 10, name: "Rose Shea Butter Soap", slug: "rose-shea-butter-soap", desc: "Deep nourishment, perfect for dry & sensitive skin.", longDesc: "A luxurious blend of rose petals and pure shea butter. Provides deep moisturization that lasts all day, making it ideal for dry, sensitive, or mature skin. The gentle rose fragrance uplifts your senses.", price: 310, tag: "Deep Moisture", cat: "Soaps", img: "/images/rose_soap.jpg", ingredients: ["Rose Petals", "Shea Butter", "Rose Hip Oil", "Vitamin E"] },
  { id: 11, name: "Coffee & Oat Milk Robust", slug: "coffee-oat-milk-soap", desc: "Reduces hormonal acne, rich in antioxidants.", longDesc: "Ground coffee beans gently exfoliate while providing a caffeine boost that tightens and firms skin. Oat milk soothes inflammation and reduces hormonal acne. A powerhouse combination for problem skin.", price: 300, tag: "Antioxidant", cat: "Soaps", img: "/images/coffee_soap.jpg", badge: "New", ingredients: ["Coffee Grounds", "Oat Milk", "Cocoa Butter", "Vitamin E"] },
  { id: 12, name: "Herbal VapoRub", slug: "herbal-vaporub", desc: "Eucalyptus, cajeput & peppermint \u2014 clear congestion. 17g", longDesc: "A natural alternative to chemical vapor rubs. Eucalyptus, cajeput, and peppermint essential oils work together to clear nasal congestion, ease breathing, and soothe chest colds and muscle aches with gentle warming relief.", price: 150, tag: "Herbal", cat: "Body", img: "/images/vaporub.jpg", ingredients: ["Eucalyptus Oil", "Cajeput Oil", "Peppermint Oil", "Shea Butter"] },
  { id: 13, name: "Goat Milk & Honey Almond Lotion", slug: "goat-milk-honey-almond-lotion", desc: "Deeply nourishes, hydrates & softens skin. 120ml", longDesc: "A rich body lotion made with pure goat milk, raw honey, and sweet almond oil. Goat milk treats eczema symptoms, honey nourishes deeply, and almond oil fights acne while curing dry skin. 120ml bottle.", price: 450, tag: "Hydrating", cat: "Body", img: "/images/lotion.jpg", badge: "Bestseller", ingredients: ["Goat Milk", "Raw Honey", "Almond Oil", "Vitamin E"] },
  { id: 14, name: "Hibiscus Shampoo & Conditioner", slug: "hibiscus-shampoo-conditioner", desc: "Pearl-infused formula for silky, shiny hair. 200ml", longDesc: "A luxurious pearl-infused 2-in-1 formula that cleanses and conditions in one step. Hibiscus extracts nourish the scalp and promote hair growth while pearl proteins add brilliant shine and smoothness. 200ml.", price: 500, tag: "Pearl-Infused", cat: "Hair", img: "/images/hibiscus_shampoo.jpg", badge: "Bestseller", ingredients: ["Hibiscus Extract", "Pearl Protein", "Biotin", "Argan Oil"] },
  { id: 15, name: "Amla & Bhringraj Shampoo & Conditioner", slug: "amla-bhringraj-shampoo-conditioner", desc: "Prevents premature greying, controls dandruff. 200ml", longDesc: "True Amla rich in Vitamin C boosts collagen and thickens hair. Bhringraj prevents premature greying and stimulates regrowth. Pearl extracts fortify strands against damage while controlling dandruff and balancing scalp oils. 200ml.", price: 500, tag: "Anti-Greying", cat: "Hair", img: "/images/amla_shampoo.jpg", ingredients: ["Amla Extract", "Bhringraj", "Pearl Extract", "Neem Oil"] },
  { id: 16, name: "Strawberry Orange Shampoo & Conditioner", slug: "strawberry-orange-shampoo-conditioner", desc: "Strengthens follicles, reduces breakage. 200ml", longDesc: "Strawberry essence strengthens hair follicles and reduces breakage. Pearl proteins enhance shine and smoothness. Deeply moisturizes to combat frizz and tangles while revitalizing the scalp for healthier roots. 200ml.", price: 500, tag: "Anti-Breakage", cat: "Hair", img: "/images/strawberry_shampoo.jpg", badge: "New", ingredients: ["Strawberry Extract", "Orange Oil", "Pearl Protein", "Keratin"] },
  { id: 17, name: "Red Wine Hydrating Shower Gel", slug: "red-wine-hydrating-shower-gel", desc: "Antioxidants rejuvenate, improves elasticity. 200ml", longDesc: "Red wine's powerful antioxidants hydrate and rejuvenate skin with every wash. The ultra-clear formula deeply cleanses without stripping moisture, improves elasticity, reduces fine lines, and leaves skin soft and supple. 200ml.", price: 500, tag: "Antioxidant", cat: "Body", img: "/images/shower_gel.jpg", ingredients: ["Red Wine Extract", "Aloe Vera", "Glycerin", "Vitamin E"] },
  { id: 18, name: "Rosemary Lavender Hair Oil", slug: "rosemary-lavender-hair-oil", desc: "Strengthens roots, promotes thicker growth. 100ml", longDesc: "A potent blend of sweet almond, coconut, and castor oils deeply nourish the scalp. Rosemary oil stimulates growth and density while lavender oil soothes irritation and promotes balanced, shiny, manageable hair. 100ml.", price: 350, tag: "Growth Oil", cat: "Hair", img: "/images/hair_oil.jpg", badge: "Bestseller", ingredients: ["Rosemary Oil", "Lavender Oil", "Sweet Almond Oil", "Castor Oil"] },
];

export const CATEGORIES = ["All", "Soaps", "Body", "Hair"] as const;

export const REVIEWS = [
  { name: "Priya S.", location: "Bangalore", text: "The Rosemary Hair Oil has completely transformed my hair. Less fall, more shine. I\u2019m on my third bottle!", product: "Rosemary Lavender Hair Oil", rating: 5 },
  { name: "Ankit R.", location: "Mumbai", text: "Switched to the Neem soap for my acne-prone skin. Clearer skin in just 2 weeks. Will never go back to chemical soaps.", product: "Neem Herbal Soap", rating: 5 },
  { name: "Meera K.", location: "Delhi", text: "The Hibiscus Shampoo smells divine and my hair feels like silk after every wash. My husband started using it too!", product: "Hibiscus Shampoo & Conditioner", rating: 5 },
  { name: "Suresh P.", location: "Chennai", text: "Bought the Honey & Almond soap for my mother. She loves it \u2014 her dry skin has improved so much. Great gifting option.", product: "Honey & Almond Soap", rating: 5 },
  { name: "Divya M.", location: "Hyderabad", text: "The Goat Milk lotion is incredibly moisturizing without being greasy. Perfect for Indian summers.", product: "Goat Milk & Honey Almond Lotion", rating: 5 },
  { name: "Rahul T.", location: "Pune", text: "The Charcoal soap gives such a deep clean. My oily skin finally feels balanced. Excellent quality for the price.", product: "Detox Charcoal Camel Milk Soap", rating: 4 },
];

export const COMBOS = [
  { id: "combo-1", name: "Soap Trio", desc: "Pick any 3 soaps", discount: 10, minItems: 3, cat: "Soaps" },
  { id: "combo-2", name: "Hair Care Bundle", desc: "Any shampoo + hair oil", discount: 12, minItems: 2, cat: "Hair" },
  { id: "combo-3", name: "Complete Care", desc: "Any 5 products across categories", discount: 15, minItems: 5, cat: "All" },
];

export function getProductBySlug(slug: string): Product | undefined {
  return PRODUCTS.find((p) => p.slug === slug);
}
